micronaut:
  application:
    name: mailer
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/views/**"
        paths: classpath:data
grpc:
  server:
    port: ${MAILER_GRPC_PORT:50011}
    max-inbound-message-size: 1024
  client:
    max-retry-attempts: 10
  channels:
    mailer:
      for-address: ${MAILER_GRPC_HOST:127.0.0.1}:${MAILER_GRPC_PORT:50011}
      plaintext: true
      max-retry-attempts: 10
javamail:
  enabled: true
  authentication:
    username: ${MAILER_ADDRESS}
    password: ${MAILER_ADDRESS_PASSWORD}
  properties:
    mail:
      smtp:
        host: ${MAILER_SMTP_HOST:smtp.gmail.com}
        port: ${MAILER_SMTP_PORT:587}
        ssl:
          enable: true
      pop3:
        host: ${MAILER_POP_HOST:pop.gmail.com}
        port: ${MAILER_POP_PORT:995}
        ssl:
          enable: true
kafka:
  bootstrap:
    servers: ${KAFKA_HOST:127.0.0.1}:${KAFKA_PORT:9092}
